spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/loanapp
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: fKAtT8Zfyx31ZJ5UXxW4LmWbQlQZoZI6fKAtT8Zfyx31ZJ5UXxW4LmWbQlQZoZI6fKAtT8Zfyx31ZJ5UXxW4LmWbQlQZoZI6
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days